name: Deploy to Dockerhub

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Setup Docker
        uses: docker/build-push-action@v5

      - name: Build and Publish Image
        env:
          API_KEY: ${{ secrets.API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        run: './gradlew publishImage'
