name: "Quality Checks"

on:
  push:
    branches:
      - "*"
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Run Detekt
        run: "./gradlew detekt"

      - name: Upload SARIF to GitHub using the upload-sarif action
        # https://github.com/github/codeql-action/issues/2117
        # uses: github/codeql-action/upload-sarif@v3
        uses: jsoref/github-codeql-action/upload-sarif@favor-workflow-ref
        if: github.ref == 'refs/heads/main' && (success() || failure())
        with:
          sarif_file: build/reports/detekt/detekt.sarif
