name: "Upload FAT JAR"
#
#on:
#  push:
#    tags:
#      - '*'
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Branch
#        uses: actions/checkout@v4
#
#      - name: Setup Java
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#          cache: 'gradle'
#
#      - name: Build JAR
#        run: './gradlew buildFatJar --no-daemon'
#
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-region: us-east-1
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#
#      - name: Upload JAR to S3 bucket
#        run: aws s3 cp build/libs/com.catscoffeeandkitchen.bongoapi-all.jar s3://${{ secrets.S3_BUCKET }}/bongo-${{ github.ref }}.jar
#
#      - name: Create new ElasticBeanstalk Application Version
#        run: |
#          aws elasticbeanstalk create-application-version \
#          --application-name BongoAPI \
#          --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="bongo-${{ github.ref }}.jar" \
#          --version-label "ver-${{ github.sha }}" \
#          --description "commit-sha-${{ github.sha }}"
#
#      - name: Deploy new ElasticBeanstalk Application Version
#        run: aws elasticbeanstalk update-environment --environment-name BongoAPI-prod --version-label "ver-${{ github.sha }}"
#
#      - name: Rename JAR for Release
#        run: mv build/libs/com.catscoffeeandkitchen.bongoapi-all.jar bongoapi.jar
#
#      - name: Create GitHub Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "bongoapi.jar"
#          generateReleaseNotes: true