name: "Upload FAT JAR"

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Build JAR
        run: './gradlew buildFatJar --no-daemon'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Upload package to S3 bucket
        run: aws s3 cp build/libs/com.catscoffeeandkitchen.bongoapi-all.jar s3://${{ secrets.S3_BUCKET }}

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name BongoAPI \
          --source-bundle S3Bucket="${{ secrets.S3_BUCKET }}",S3Key="bongo-${{ github.sha }}.jar" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name BongoAPI-prod --version-label "ver-${{ github.sha }}"
